name: Package & Release Plugin

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload plugin artifact
      uses: actions/upload-artifact@v4
      with:
        name: Plugin
        path: target/takion-*.jar

    - name: Get Plugin Version
      id: version
      run: echo "VERSION=$(ls target/takion-*.jar | sed -E 's/.*takion-(.*).jar/\1/')" >> $GITHUB_ENV

    - name: Delete existing GitHub release (if exists)
      run: |
        RELEASE_ID=$(gh release view v${{ env.VERSION }} --json id -q '.id' || echo "")
        if [ -n "$RELEASE_ID" ]; then
          echo "Deleting existing release..."
          gh release delete v${{ env.VERSION }} --yes
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete existing tag (if exists)
      run: |
        if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
          echo "Deleting existing tag..."
          git tag -d v${{ env.VERSION }}
          git push origin :refs/tags/v${{ env.VERSION }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        name: Release v${{ env.VERSION }}
        draft: false
        prerelease: false
        files: target/takion-*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
